Android implementation
vrtdev/flutter_qualtrics pull request #3
Opened 2019-12-18 13:55 UTC by jeremie-movify

Bound all of Qualtrics' SDK methods to plugin

2019-12-18 13:56 UTC, jeremie-movify commented
@petermnt @timrijckaert @Kymer Please review the iOS implementation PR before this one (this branch is based off the ios-implementation branch)

2019-12-20 09:10 UTC, petermnt requested changes

2019-12-20 09:10 UTC, petermnt commented on android/src/main/kotlin/be/vrt/qualtrics_flutter/QualtricsFlutterPlugin.kt
> +        Qualtrics.instance().evaluateTargetingLogic {
maybe pass an error here

2019-12-20 09:10 UTC, petermnt commented on android/src/main/kotlin/be/vrt/qualtrics_flutter/QualtricsFlutterPlugin.kt
> +            else {
else on same line :D

2019-12-20 09:27 UTC, jeremie-movify commented on android/src/main/kotlin/be/vrt/qualtrics_flutter/QualtricsFlutterPlugin.kt
> +        Qualtrics.instance().evaluateTargetingLogic {
👍

2019-12-20 10:01 UTC, petermnt approved these changes

2019-12-20 12:58 UTC, merged